/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as MethodRouteImport } from './routes/method'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as EntityIdRouteImport } from './routes/entity.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/briefing': typeof BriefingRoute
  '/compare': typeof CompareRoute
  '/entities': typeof EntitiesRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/ingest': typeof IngestRoute
  '/method': typeof MethodRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/showcase': typeof ShowcaseRoute
  '/trends': typeof TrendsRoute
  '/entity/$id': typeof EntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/briefing': typeof BriefingRoute
  '/compare': typeof CompareRoute
  '/entities': typeof EntitiesRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/ingest': typeof IngestRoute
  '/method': typeof MethodRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/showcase': typeof ShowcaseRoute
  '/trends': typeof TrendsRoute
  '/entity/$id': typeof EntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/briefing': typeof BriefingRoute
  '/compare': typeof CompareRoute
  '/entities': typeof EntitiesRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/ingest': typeof IngestRoute
  '/method': typeof MethodRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/showcase': typeof ShowcaseRoute
  '/trends': typeof TrendsRoute
  '/entity/$id': typeof EntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalies'
    | '/briefing'
    | '/compare'
    | '/entities'
    | '/evidence'
    | '/findings'
    | '/ingest'
    | '/method'
    | '/reports'
    | '/review'
    | '/showcase'
    | '/trends'
    | '/entity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalies'
    | '/briefing'
    | '/compare'
    | '/entities'
    | '/evidence'
    | '/findings'
    | '/ingest'
    | '/method'
    | '/reports'
    | '/review'
    | '/showcase'
    | '/trends'
    | '/entity/$id'
  id:
    | '__root__'
    | '/'
    | '/anomalies'
    | '/briefing'
    | '/compare'
    | '/entities'
    | '/evidence'
    | '/findings'
    | '/ingest'
    | '/method'
    | '/reports'
    | '/review'
    | '/showcase'
    | '/trends'
    | '/entity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomaliesRoute: typeof AnomaliesRoute
  BriefingRoute: typeof BriefingRoute
  CompareRoute: typeof CompareRoute
  EntitiesRoute: typeof EntitiesRoute
  EvidenceRoute: typeof EvidenceRoute
  FindingsRoute: typeof FindingsRoute
  IngestRoute: typeof IngestRoute
  MethodRoute: typeof MethodRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TrendsRoute: typeof TrendsRoute
  EntityIdRoute: typeof EntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomaliesRoute: AnomaliesRoute,
  BriefingRoute: BriefingRoute,
  CompareRoute: CompareRoute,
  EntitiesRoute: EntitiesRoute,
  EvidenceRoute: EvidenceRoute,
  FindingsRoute: FindingsRoute,
  IngestRoute: IngestRoute,
  MethodRoute: MethodRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  ShowcaseRoute: ShowcaseRoute,
  TrendsRoute: TrendsRoute,
  EntityIdRoute: EntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
